version: '2'

services:
    django:
        build:
            context: .
            dockerfile: docker/Dockerfile-django
        volumes:
            - "./projement:/app"
        environment:
            - PYTHONUNBUFFERED=0
            - PYTHONPYCACHEPREFIX=../__pycache__
        ports:
            - "8000:8000"
        command: python manage.py runserver 0.0.0.0:8000

    node:
        build:
            context: .
            dockerfile: docker/Dockerfile-node
        volumes:
            - ".data/node_modules:/app/node_modules"
            - "./projement:/app"
